{% set version = "0.22.1" %}

package:
  name: hypothesis-jsonschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hypothesis-jsonschema/hypothesis-jsonschema-{{ version }}.tar.gz
  sha256: 5dd7449009f323e408a9aa64afb4d18bd1f60ea2eabf5bf152a510da728b34f2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - hypothesis >=6.31.6
    - jsonschema >=4.0.0
    - python >=3.7

test:
  imports:
    - hypothesis_jsonschema

about:
  home: https://github.com/Zac-HD/hypothesis-jsonschema
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Tools to generate test data from JSON schemata with Hypothesis
  dev_url: https://github.com/Zac-HD/hypothesis-jsonschema

extra:
  recipe-maintainers:
    - bollwyvl
