{% set name = "hypothesis-jsonschema" %}
{% set version = "0.19.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6382a2789c36cad15d9bdf543b9b64d421bc411580a3a24a9daaee0804beae2a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - hypothesis >=5.3.0
    - jsonschema >=3.0.2
    - python >=3.6

test:
  imports:
    - hypothesis_jsonschema

about:
  home: https://github.com/Zac-HD/hypothesis-jsonschema
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Tools to generate test data from JSON schemata with Hypothesis
  dev_url: https://github.com/Zac-HD/hypothesis-jsonschema

extra:
  recipe-maintainers:
    - bollwyvl
