{% set name = "hypothesis-jsonschema" %}
{% set version = "0.9.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b641b9ce5c1b076e48c8f74b58450407774062d0db5d13efc6f822a8c9c07c9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - hypothesis >=4.5.0
    - jsonschema >=3.0.2

test:
  imports:
    - hypothesis_jsonschema

about:
  home: https://github.com/Zac-HD/hypothesis-jsonschema
  license: MPL-2.0
  license_family: Other
  # TODO: Remove after https://github.com/Zac-HD/hypothesis-jsonschema/pull/21
  license_file: mpl-2.0.txt
  summary: 'Tools to generate test data from JSON schemata with Hypothesis'
  dev_url: https://github.com/Zac-HD/hypothesis-jsonschema

extra:
  recipe-maintainers:
    - bollwyvl
