travis:
  secure:
    BINSTAR_TOKEN: tfhGDH0c4jPK9Au6Aba0sUwNwqdIzraTP3hBOrPlqp9EKxv1hDRHSjccIbcsbscFCKVBCLFDY9AxVdlOTTruTTGFnxkgZWsOP3+zvi1/CtREzGZZisYpznsobPWCz9J14AJlfkugwx0uT9fXHLshfCLew7QbEpgAGzthBBfgPowMtOlF+YD+lzhUIlxp9NS9M0pDhVzc1tTVEa+ReltdvUjT67vD1JGgytMgGfOcPDVeiBdgW7knU3N9ruOtRFWsH31qNBE5glmcqStZibUZj5bjdRqWdI5ndXfaNZklmwVqOZoVd8Iy0PnCy41Ft3R9s1dyNQN5AGIzAPWyZV85+vk/lFUNFmaxUw93GePDGSQMO3WOcxTEjhgDzY9wck9iVnr2LntDvUfq4v+MgsJ8tdCfqkgYhmEg3rh2VKDDwD/9nGf9wuR/vECrkJZ1LACi+IGWsr1UIdypqHktuHJUbonetqkoMJ6uUbME5EO3G9ToBCASEzfvMvTXpcL/PMwute6ZyHjxD47pvHsDLsXm/WWPvcSIzDkLzkYsNRcAXBu5rV/HeLM4z5h+nP5z4mrqJdElVdW0gWDudHrsNd2J1m9UexwIRBeqOkNnMMzJhRCzMj4ob90hc+FCy8aFC54SYSQEW0pjWCv9ieBi69os8UBg4FX7VSdUg2JuiSXhsn4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
